# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:37
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20160507_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='start_tz',
            field=timezone_field.fields.TimeZoneField(default=b'America/Los_Angeles', help_text='Challenge Timezone', verbose_name='Timezone'),
        ),
    ]
