# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20160507_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='day_of_month',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19'), (b'20', b'20'), (b'21', b'21'), (b'22', b'22'), (b'23', b'23'), (b'24', b'24'), (b'25', b'25'), (b'26', b'26'), (b'27', b'27'), (b'28', b'28'), (b'29', b'29'), (b'30', b'30'), (b'31', b'31')], help_text='Day of Month', max_length=10, null=True, verbose_name='Day of Month'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='day_of_week',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[(b'0', 'Sunday'), (b'1', 'Monday'), (b'2', 'Tuesday'), (b'4', 'Wednesday'), (b'8', 'Thursday'), (b'16', 'Friday'), (b'32', 'Saturday')], help_text='Day of Week', max_length=10, null=True, verbose_name='Day of Week'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='month',
            field=select_multiple_field.models.SelectMultipleField(blank=True, choices=[(b'0', 'January'), (b'1', 'February'), (b'2', 'March'), (b'4', 'April'), (b'8', 'May'), (b'16', 'June'), (b'32', 'July'), (b'64', 'August'), (b'128', 'September'), (b'256', 'October'), (b'512', 'November'), (b'1024', 'December')], help_text='Month', max_length=10, null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='recurrence',
            field=models.CharField(choices=[(b'0', 'Dateless'), (b'1', 'Once'), (b'2', 'Weekly'), (b'4', 'Monthly'), (b'8', 'Annually'), (b'16', 'Custom')], default=b'1', help_text='Challenge Recurrence', max_length=10, verbose_name='Recurrence'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='acceptance_text',
            field=models.TextField(blank=True, help_text='This Text will automatically appear as an Acknowledgment Text for each Participant after Challenge has been marked as completed.', null=True, verbose_name='Acceptance Text'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, help_text='Challenge Start Date', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_time',
            field=models.TimeField(blank=True, db_index=True, help_text='Challenge Start Time', null=True, verbose_name='Start Time'),
        ),
    ]
