# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20160822_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='addressless',
            field=models.BooleanField(default=False),
        ),
    ]
