# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import select_multiple_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20161227_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='allow_reenter',
            field=models.BooleanField(default=False, help_text='Allow Members to apply again to the Challenge after withdrawing their Application.', verbose_name='Allow Members to apply again to the Challenge after withdrawing their Application.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='day_of_month',
            field=select_multiple_field.models.SelectMultipleField(choices=[(b'0', '----------'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5'), (b'6', b'6'), (b'7', b'7'), (b'8', b'8'), (b'9', b'9'), (b'10', b'10'), (b'11', b'11'), (b'12', b'12'), (b'13', b'13'), (b'14', b'14'), (b'15', b'15'), (b'16', b'16'), (b'17', b'17'), (b'18', b'18'), (b'19', b'19'), (b'20', b'20'), (b'21', b'21'), (b'22', b'22'), (b'23', b'23'), (b'24', b'24'), (b'25', b'25'), (b'26', b'26'), (b'27', b'27'), (b'28', b'28'), (b'29', b'29'), (b'30', b'30'), (b'31', b'31'), (b'32', 'Last Day of Month')], default=b'0', help_text='Day of Month', max_length=64, verbose_name='Day of Month'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='recurrence',
            field=models.CharField(choices=[(b'0', 'Dateless'), (b'1', 'Once')], default=b'1', help_text='Challenge Recurrence', max_length=10, verbose_name='Recurrence'),
        ),
    ]
