# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:23
from __future__ import unicode_literals

import autoslug.fields
import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20170520_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='avatar',
            field=models.ImageField(upload_to=challenges.models.challenge_directory_path),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True),
        ),
    ]
