# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20170918_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='achievements',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Achievements', null=True, verbose_name='Achievements'),
        ),
    ]
