# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_challenge_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(blank=True, choices=[(b'0', 'Animals'), (b'1', 'Arts & Culture'), (b'2', 'Children & Youth'), (b'4', 'Community'), (b'8', 'Education & Literacy'), (b'16', 'Environment'), (b'32', 'Health & Wellness'), (b'64', 'Sports & Recreation'), (b'128', 'Veterans & Seniors')], help_text='Challenge Category', max_length=4, null=True, verbose_name='Category'),
        ),
    ]
