# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 22:19
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_auto_20180223_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='alt_person_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please, use the International Format, e.g. +1-202-555-0114.', max_length=128, null=True, verbose_name='Phone Number'),
        ),
    ]
