# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 18:50
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_auto_20180223_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, help_text='Category Name', max_length=80, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Category Description', null=True, verbose_name='Description')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True)),
                ('category', models.CharField(blank=True, choices=[(b'0', 'Animals'), (b'1', 'Arts & Culture'), (b'2', 'Children & Youth'), (b'4', 'Community'), (b'8', 'Education & Literacy'), (b'16', 'Environment'), (b'32', 'Health & Wellness'), (b'64', 'Sports & Recreation'), (b'128', 'Veterans & Seniors')], help_text='Category', max_length=4, null=True, verbose_name='Category')),
                ('color', models.CharField(blank=True, choices=[(b'0', b'DarkKhaki'), (b'1', b'LightSteelBlue'), (b'2', b'SlateBlue'), (b'4', b'DarkOrange'), (b'8', b'#DEB887'), (b'16', b'Green'), (b'32', b'Red'), (b'64', b'LightSeaGreen'), (b'128', b'SaddleBrown')], help_text='Category Color', max_length=4, null=True, verbose_name='Color')),
                ('icon', models.CharField(blank=True, choices=[(b'0', b'fa fa-paw fa-fw'), (b'1', b'fa fa-wrench fa-fw'), (b'2', b'fa fa-child fa-fw'), (b'4', b'fa fa-users fa-fw'), (b'8', b'fa fa-book fa-fw'), (b'16', b'fa fa-tree fa-fw'), (b'32', b'fa fa-heartbeat fa-fw'), (b'64', b'fa fa-bicycle fa-fw'), (b'128', b'fa fa-home fa-fw')], help_text='Category Color', max_length=4, null=True, verbose_name='Color')),
                ('image', models.CharField(blank=True, choices=[(b'0', b'/static/img/challenge-categories/1-animals.jpeg'), (b'1', b'/static/img/challenge-categories/2-arts-and-culture.jpeg'), (b'2', b'/static/img/challenge-categories/3-children-and-youth.jpeg'), (b'4', b'/static/img/challenge-categories/4-community.jpeg'), (b'8', b'/static/img/challenge-categories/5-education-and-literacy.jpeg'), (b'16', b'/static/img/challenge-categories/6-environment-2.jpeg'), (b'32', b'/static/img/challenge-categories/7-health-and-wellness.jpeg'), (b'64', b'/static/img/challenge-categories/8-sports-and-recreation.jpeg'), (b'128', b'/static/img/challenge-categories/9-veterans-and-seniors.ljpeg')], help_text='Category Image', max_length=4, null=True, verbose_name='Image')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
