# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 19:41
from __future__ import unicode_literals

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0016_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=challenges.models.challenge_category_directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[(b'0', b'fa fa-paw fa-fw'), (b'1', b'fa fa-wrench fa-fw'), (b'2', b'fa fa-child fa-fw'), (b'4', b'fa fa-users fa-fw'), (b'8', b'fa fa-book fa-fw'), (b'16', b'fa fa-tree fa-fw'), (b'32', b'fa fa-heartbeat fa-fw'), (b'64', b'fa fa-bicycle fa-fw'), (b'128', b'fa fa-home fa-fw')], help_text='Category Icon', max_length=4, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, choices=[(b'0', b'/img/challenge-categories/1-animals.jpeg'), (b'1', b'/img/challenge-categories/2-arts-and-culture.jpeg'), (b'2', b'/img/challenge-categories/3-children-and-youth.jpeg'), (b'4', b'/img/challenge-categories/4-community.jpeg'), (b'8', b'/img/challenge-categories/5-education-and-literacy.jpeg'), (b'16', b'/img/challenge-categories/6-environment-2.jpeg'), (b'32', b'/img/challenge-categories/7-health-and-wellness.jpeg'), (b'64', b'/img/challenge-categories/8-sports-and-recreation.jpeg'), (b'128', b'/img/challenge-categories/9-veterans-and-seniors.ljpeg')], help_text='Category Image', max_length=4, null=True, verbose_name='Image'),
        ),
    ]
