# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0017_auto_20180306_1141'),
        ('challenges', '0016_auto_20180311_1519'),
    ]

    operations = [
    ]
