# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0018_merge_20180314_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, choices=[(b'0', b'/img/challenge-categories/1-animals.jpeg'), (b'1', b'/img/challenge-categories/2-arts-and-culture.jpeg'), (b'2', b'/img/challenge-categories/3-children-and-youth.jpeg'), (b'4', b'/img/challenge-categories/4-community.jpeg'), (b'8', b'/img/challenge-categories/5-education-and-literacy.jpeg'), (b'16', b'/img/challenge-categories/6-environment-2.jpeg'), (b'32', b'/img/challenge-categories/7-health-and-wellness.jpeg'), (b'64', b'/img/challenge-categories/8-sports-and-recreation.jpeg'), (b'128', b'/img/challenge-categories/9-veterans-and-seniors.jpeg')], help_text='Category Image', max_length=4, null=True, verbose_name='Image'),
        ),
    ]
