# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
    ]
