# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:23
from __future__ import unicode_literals

import autoslug.fields
import blog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160822_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(upload_to=blog.models.blog_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Post Content', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique=True),
        ),
    ]
