# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 20:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170918_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Post Content', null=True, verbose_name='Content'),
        ),
    ]
