# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 21:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170918_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Post short Description', null=True, verbose_name='Short Description'),
        ),
    ]
