# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 21:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20170918_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(db_index=True, help_text='Section Title', max_length=60, verbose_name='Title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Section Order (auto-incremented)', verbose_name='Order')),
                ('author', models.ForeignKey(blank=True, help_text='Section Author', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_faq_sections', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.AddField(
            model_name='faq',
            name='section',
            field=models.ForeignKey(default=None, help_text='FAQ Section', on_delete=django.db.models.deletion.CASCADE, related_name='related_faqs', to='home.Section', verbose_name='Section'),
            preserve_default=False,
        ),
    ]
