# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160504_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=b'', help_text='User Bio', null=True, verbose_name=b'Bio'),
        ),
    ]
