# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160509_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, default=b'', help_text='User Nickname', max_length=32, null=True, verbose_name='Nickname'),
        ),
    ]
