# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160517_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'2', 'Other'), (b'1', 'Male'), (b'0', 'Female')], default=b'0', help_text='User Gender', max_length=2, verbose_name='Gender'),
        ),
    ]
