# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20160525_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacyAdmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_details', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'2', help_text='Who can see my Profile Details (e.g. Avatar, Name, Bio, Gender, Birthday)', max_length=2, verbose_name='Who can see my Profile Details (e.g. Avatar, Name, Bio, Gender, Birthday)')),
                ('contact_details', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'0', help_text='Who can see my Contact Details (e.g. Address, Phone #, Email)', max_length=2, verbose_name='Who can see my Contact Details (e.g. Address, Phone #, Email)')),
                ('challenges_upcoming', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'2', help_text="Who can see the List of Challenges, I'm going to participate in (upcoming Challenges)", max_length=2, verbose_name="Who can see the List of Challenges, I'm going to participate in (upcoming Challenges)")),
                ('challenges_completed', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'2', help_text='Who can see the List of Challenges, I participated in (completed Challenges)', max_length=2, verbose_name='Who can see the List of Challenges, I participated in (completed Challenges)')),
                ('challenges_affiliated', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'2', help_text='Who can see the List of Challenges, I affiliated with ', max_length=2, verbose_name='Who can see the List of Challenges, I affiliated with ')),
                ('participations_canceled', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'1', help_text='Who can see the List of Participations, canceled by me (withdrawn Participations)', max_length=2, verbose_name='Who can see the List of Participations, canceled by me (withdrawn Participations)')),
                ('participations_rejected', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Admins of the Challenges, I participate(-d) in'), (b'2', 'Admins of the upcoming Challenges on the Platform')], default=b'1', help_text='Who can see the List of Participations, canceled by the Challenge Organizer/Admin (rejected Participations)', max_length=2, verbose_name='Who can see the List of Participations, canceled by the Challenge Organizer/Admin (rejected Participations)')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_admins', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'verbose_name': 'user privacy (admins)',
                'verbose_name_plural': 'user privacy (admins)',
            },
        ),
        migrations.CreateModel(
            name='UserPrivacyGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('hide_profile_from_search', models.BooleanField(default=False, help_text='Hide my Profile from the Search Results', verbose_name='Hide my Profile from the Search Results')),
                ('hide_profile_from_list', models.BooleanField(default=False, help_text="Hide my Profile from the Members' List", verbose_name="Hide my Profile from the Members' List")),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_general', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'verbose_name': 'user privacy (general)',
                'verbose_name_plural': 'user privacy (general)',
            },
        ),
        migrations.CreateModel(
            name='UserPrivacyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_details', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'1', help_text='Who can see my Profile Details (e.g. Avatar, Name, Bio, Gender, Birthday)', max_length=2, verbose_name='Who can see my Profile Details (e.g. Avatar, Name, Bio, Gender, Birthday)')),
                ('contact_details', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'0', help_text='Who can see my Contact Details (e.g. Address, Phone #, Email)', max_length=2, verbose_name='Who can see my Contact Details (e.g. Address, Phone #, Email)')),
                ('challenges_upcoming', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'2', help_text="Who can see the List of Challenges, I'm going to participate in (upcoming Challenges)", max_length=2, verbose_name="Who can see the List of Challenges, I'm going to participate in (upcoming Challenges)")),
                ('challenges_completed', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'2', help_text='Who can see the List of Challenges, I participated in (completed Challenges)', max_length=2, verbose_name='Who can see the List of Challenges, I participated in (completed Challenges)')),
                ('challenges_affiliated', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'1', help_text='Who can see the List of Challenges, I affiliated with ', max_length=2, verbose_name='Who can see the List of Challenges, I affiliated with ')),
                ('participations_canceled', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'4', help_text='Who can see the List of Participations, canceled by me (withdrawn Participations)', max_length=2, verbose_name='Who can see the List of Participations, canceled by me (withdrawn Participations)')),
                ('participations_rejected', models.CharField(choices=[(b'0', 'No-one'), (b'1', 'Registered Users'), (b'2', 'Participants of the Challenges, I participate in too'), (b'4', 'Staff/Group Members of the Organization(s), I affiliated with'), (b'8', 'Everyone')], default=b'4', help_text='Who can see the List of Participations, canceled by the Challenge Organizer/Admin (rejected Participations)', max_length=2, verbose_name='Who can see the List of Participations, canceled by the Challenge Organizer/Admin (rejected Participations)')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='privacy_members', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
                'verbose_name': 'user privacy (members)',
                'verbose_name_plural': 'user privacy (members)',
            },
        ),
    ]
