# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprivacyadmins_userprivacygeneral_userprivacymembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy_mode',
        ),
    ]
