# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_populate_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'0', 'Female'), (b'1', 'Male'), (b'2', 'Other')], default=b'0', help_text='User Gender', max_length=2, verbose_name='Gender'),
        ),
    ]
