# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:23
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160822_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
