# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170918_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_newly_created',
            field=models.BooleanField(default=True),
        ),
    ]
