# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170323_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='mobile_phone_number_ext',
            field=models.CharField(blank=True, help_text='Ext.', max_length=8, null=True, verbose_name='Ext.'),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_number_ext',
            field=models.CharField(blank=True, help_text='Ext.', max_length=8, null=True, verbose_name='Ext.'),
        ),
    ]
