# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170329_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='notes',
            field=models.TextField(blank=True, help_text='Here you can provide additional Notes, Directions, and any other Advice, regarding the Venue Location.', null=True, verbose_name='Notes'),
        ),
    ]
