# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_address_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtttachedUrl',
            new_name='AttachedUrl',
        ),
        migrations.AlterField(
            model_name='address',
            name='notes',
            field=models.TextField(blank=True, help_text='Here you can provide additional Notes, Directions, and any other Advice, regarding the Location.', null=True, verbose_name='Notes'),
        ),
    ]
