# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170518_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_1',
            field=models.CharField(blank=True, db_index=True, help_text='Address Line 1', max_length=80, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, db_index=True, help_text='Address Line 2', max_length=80, null=True, verbose_name='Address Line 2'),
        ),
    ]
