# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-14 20:26
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20170520_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('text', models.TextField(help_text='Complaint Text', verbose_name=b'Text')),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaints',
            },
        ),
        migrations.AlterField(
            model_name='attacheddocument',
            name='document',
            field=models.FileField(upload_to=core.models.attachment_document_directory_path),
        ),
        migrations.AlterField(
            model_name='attachedimage',
            name='image',
            field=models.ImageField(upload_to=core.models.attachment_image_directory_path),
        ),
        migrations.AlterField(
            model_name='temporaryfile',
            name='file',
            field=models.FileField(upload_to=core.models.tmp_directory_path),
        ),
    ]
