# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180301_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, db_index=True, help_text='Zip/Postal Code', max_length=80, null=True, verbose_name='Zip/Postal Code'),
        ),
    ]
