# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 01:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_addressless'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstaff',
            options={'ordering': ['order'], 'verbose_name': 'organization staff member', 'verbose_name_plural': 'organization staff members'},
        ),
        migrations.AddField(
            model_name='organizationstaff',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(upload_to=organizations.models.organization_directory_path),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True),
        ),
    ]
