# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20170903_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscribers',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Organization Subscribers', related_name='organization_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AlterField(
            model_name='organizationgroup',
            name='members',
            field=models.ManyToManyField(blank=True, db_index=True, help_text='Organization Group Member', related_name='organization_group_members', to=settings.AUTH_USER_MODEL, verbose_name='Group Member'),
        ),
    ]
