# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived', verbose_name='Archived'),
        ),
    ]
