# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_invite_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='invite',
            name='is_archived_for_invitee',
            field=models.BooleanField(default=False, help_text='Archived for Invitee', verbose_name='Archived for Invitee'),
        ),
        migrations.AddField(
            model_name='invite',
            name='is_archived_for_inviter',
            field=models.BooleanField(default=False, help_text='Archived for Inviter', verbose_name='Archived for Inviter'),
        ),
    ]
